### PR TITLE
Added dropHandler support via a drop view

### PR DESCRIPTION
**Pull request by Dejal**
When a drop handler is set, a CCNStatusItemDropView is added as a
subview of the status item button.  That receives drops, and passes the
dropped objects to the handler.  By default it accepts file paths, but
a dropTypes property can be set to accept other types.

### CODE REVIEW

**Comment by Dejal** [comment]
Example usage:

        CCNStatusItem *sharedItem = [CCNStatusItem sharedInstance];
        
        sharedItem.windowConfiguration.presentationTransition = CCNPresentationTransitionSlideAndFade;
        sharedItem.proximityDragDetectionEnabled = NO;
        
        [sharedItem presentStatusItemWithImage:[NSImage imageNamed:@"StatusIdleTemplate"]
            contentViewController:self.viewController
            dropHandler:^(CCNStatusItem *sharedItem, NSString *pasteboardType, NSArray *droppedObjects) {
                NSLog(@"dropped: %@", droppedObjects);
            }];

The proximity drag detection feature is nice, but not needed for the drop handler.  It could still be useful if the status content view controller receives drags instead.

**Comment by Dejal** [comment]
Just noticed that the demo project won't build because the new `CCNStatusItemDropView` needs to be added to the project.  You can do that if you wish, or let me know if you want me to do it via another pull request.

**Comment by phranck** [comment]
You can do it. It will be added to the same PR. Thanks.

**Comment by Dejal** [comment]
Done.

**Comment by phranck** [comment]
@Dejal Thank you very much for adding the Drag&Drop feature! I made some minor changes and adapted the example application.

**Comment by phranck** [comment]
@Dejal Note: If you are using it in a published software you can add a note at the bottom of the [ReadMe](https://github.com/phranck/CCNStatusItem/blob/master/ReadMe.md).

**Comment by Dejal** [comment]
You're welcome.  It is used in a client app that hasn't been released or announced yet, but I'll try to remember to update the readme once it is public.  (I'll probably use it in a future version of my own Time Out app, too.)

**Pull request merged**
